---
- name: Format block device.
  filesystem:
      fstype: ext4
      dev: /dev/xvdf
      force: yes
  tags:
      - install_jenkins

- name: Ensure jenkins_home mountpoint exists.
  file: 
      path: /var/jenkins_home
      state: directory
      owner: root
      group: root
      mode: 755
  tags:
      - install_jenkins

- name: Mount block device onto mountpoint
  mount:
      path: /var/jenkins_home
      src: /dev/xvdf
      fstype: ext4
      state: mounted
  tags:
      - install_jenkins
