FROM jenkins

USER root

RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - \
        && apt-get update && apt-get install -y \
            nodejs \
        && rm -rf /var/lib/apt/lists/*

USER jenkins

