version: '2'
services:
    jenkins:
        image: jenkins
        container_name: jenkins
        ports: 
            - '80:8080'
            - '5000:5000'
        volumes:
            - './jenkins_home:/var/jenkins_home'
            - './:/docker-ci'
