---
Outputs:
    EcrRepoName: 
        Description: The name of the ECR repo
        Value: !Ref "EcrRepo"

    JenkinsIp:
        Description: The public IP address of the jenkins instance
        Value: !GetAtt Jenkins.PublicIp

Resources:

    EcrRepo:
        Type: AWS::ECR::Repository
        Properties:
            RepositoryPolicyText:
                Version: "2012-10-17"
                Statement:
                    - Effect: "Allow"
                      Action: 
                        - "ecr:GetDownloadUrlForLayer"
                        - "ecr:BatchGetImage"
                        - "ecr:BatchCheckLayerAvailability"
                      Principal:
                          AWS:
                              - !GetAtt JenkinsRole.Arn

    Vpc:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.0.0.0/16

    InternetGateway:
        Type: AWS::EC2::InternetGateway

    AttachInternetGateway:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            InternetGatewayId: !Ref "InternetGateway"
            VpcId: !Ref "Vpc"

    PublicRouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref "Vpc"

    PublicRoute:
        Type: AWS::EC2::Route
        Properties:
            DestinationCidrBlock: 0.0.0.0/0
            GatewayId: !Ref "InternetGateway"
            RouteTableId: !Ref "PublicRouteTable"
        DependsOn: InternetGateway

    PublicSubnet:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: eu-west-1a
            CidrBlock: 10.0.0.0/24
            MapPublicIpOnLaunch: 'true'
            VpcId: !Ref "Vpc"

    PublicSubnetRouteTable:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref "PublicRouteTable"
            SubnetId: !Ref "PublicSubnet"

    JenkinsSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Security group for Jenkins instance
            VpcId: !Ref "Vpc"
            SecurityGroupIngress:
                - CidrIp: 0.0.0.0/0
                  FromPort: 22
                  IpProtocol: tcp
                  ToPort: 22
                - CidrIp: 0.0.0.0/0
                  FromPort: 80
                  IpProtocol: tcp
                  ToPort: 80
                - CidrIp: 0.0.0.0/0
                  FromPort: 2376
                  IpProtocol: tcp
                  ToPort: 2376

    JenkinsRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement: 
                    - Effect: "Allow"
                      Principal: 
                          Service: "ec2.amazonaws.com"
                      Action: "sts:AssumeRole"

    JenkinsProfile: 
        Type: AWS::IAM::InstanceProfile
        Properties:
            Roles:
                - !Ref "JenkinsRole"

    Jenkins:
        Type: AWS::EC2::Instance
        Properties:
            IamInstanceProfile: !Ref "JenkinsProfile"
            ImageId: ami-01ccc867
            InstanceType: t2.micro
            KeyName: kieranbamforth
            SecurityGroupIds: 
                - !GetAtt JenkinsSecurityGroup.GroupId
            SubnetId: !Ref "PublicSubnet"
