version: '2'
services:
    jenkins:
        image: ${REGISTRY_URI}:latest
        container_name: jenkins
        ports: 
            - '80:8080'
            - '5000:5000'
        volumes:
            - '/var/jenkins_home/config.xml:/var/jenkins_home/config.xml'
            - '/var/run/docker.sock:/var/run/docker.sock'
